### PR TITLE
refactor(go mod): migrate to go modules

### LINKED ISSUE #1355: Migrating to Go Modules
Since Go 1.11, go includes Modules which is a dependency management system that makes dependency version information explicit and easier to use.

Please refer to the following two blogposts to understand and read more about using Go modules, and migrating to Go modules.

1. [Using Go Modules](https://blog.golang.org/using-go-modules) > 2. [Migrating to Go Modules](https://blog.golang.org/migrating-to-go-modules) >  > Using Go modules will enable us to easily manage dependencies and also run Go programs outside the GOPATH. We don't need to specify the GOPATH anymore.
2. [Here](https://medium.com/@fonseka.live/getting-started-with-go-modules-b3dac652066d) you can read more about using Go modules.

### PR DESCRIPTION
**Pull request by cndoit18**
During the migration process, some code is updated directly in the vendor folder, causing inconsistent with the upstream code repository.
I move this part of the code to the migrate
folder.

fixes #1355 

Signed-off-by: cndoit18 <cndoit18@outlook.com>

### CODE REVIEW

**Comment by cndoit18** [comment]
In order to completely abolish the vendor, we also need some work to migrate the code from the migrate folder to the official version.

**Comment by cndoit18** [comment]
cc @shlomi-noach

**Comment by shlomi-noach** [comment]
Thank you! I can take a look into those changes. Appreciate the kick off!

**Comment by cndoit18** [comment]
> Thank you! I can take a look into those changes. Appreciate the kick off!

Creating a vendor folder is to compatible downstream, if you need, you can delete it to test

I just used `go mod vendor`.

**Comment by cndoit18** [comment]
I will try to fix the repair, simply verify the test of CI.

**Comment by shlomi-noach** [comment]
thanks again - commit https://github.com/openark/orchestrator/pull/1356/commits/3d33edf9c0e7098d1d612dec7abcbeb89de65d22 modifies the raft logic - I'd like to avoid that. If we switch to `go modules` then that's what we should be doing, without logic changes.
I have indeed updated the raft library inline, because my contribution upstream was not accepted. Alas, this is how it has to stay - `upstream` has diverged since then in a completely different direction, and I don't wish to try and sync with it again.

So I don't mind creating e.g. a `openark/raft` repo, and use a `replace { ... }` directive to point to that repo. Same for `golib`, if needed. What do you think?

**Comment by cndoit18** [comment]
> thanks again - commit [3d33edf](https://github.com/openark/orchestrator/commit/3d33edf9c0e7098d1d612dec7abcbeb89de65d22) modifies the raft logic - I'd like to avoid that. If we switch to `go modules` then that's what we should be doing, without logic changes.
> I have indeed updated the raft library inline, because my contribution upstream was not accepted. Alas, this is how it has to stay - `upstream` has diverged since then in a completely different direction, and I don't wish to try and sync with it again.
> 
> So I don't mind creating e.g. a `openark/raft` repo, and use a `replace { ... }` directive to point to that repo. Same for `golib`, if needed. What do you think?

it is so good, I have rollback the code and deleted the vendor. Looking forward to your `openark/raft`

**Comment by cndoit18** [comment]
> thanks again - commit [3d33edf](https://github.com/openark/orchestrator/commit/3d33edf9c0e7098d1d612dec7abcbeb89de65d22) modifies the raft logic - I'd like to avoid that. If we switch to `go modules` then that's what we should be doing, without logic changes.
> I have indeed updated the raft library inline, because my contribution upstream was not accepted. Alas, this is how it has to stay - `upstream` has diverged since then in a completely different direction, and I don't wish to try and sync with it again.
> 
> So I don't mind creating e.g. a `openark/raft` repo, and use a `replace { ... }` directive to point to that repo. Same for `golib`, if needed. What do you think?

and, I didn't find the commit record corresponding to `github.com/openark/golib`. can you push it?

these changes are recorded in migrate

**Comment by cndoit18** [comment]
> thanks again - commit [3d33edf](https://github.com/openark/orchestrator/commit/3d33edf9c0e7098d1d612dec7abcbeb89de65d22) modifies the raft logic - I'd like to avoid that. If we switch to `go modules` then that's what we should be doing, without logic changes.
> I have indeed updated the raft library inline, because my contribution upstream was not accepted. Alas, this is how it has to stay - `upstream` has diverged since then in a completely different direction, and I don't wish to try and sync with it again.
> 
> So I don't mind creating e.g. a `openark/raft` repo, and use a `replace { ... }` directive to point to that repo. Same for `golib`, if needed. What do you think?

This is too good.

**Comment by cndoit18** [comment]
dependency on https://github.com/openark/golib/pull/10

**Comment by cndoit18** [comment]
We have successfully switched to go modules!
Next, we can add a cache. same like Dockerfile
And migrated to golang 1.16
It is very big, I think it should be divided into multiple PR.
WDYT @shlomi-noach 

https://github.com/presslabs/mysql-operator/pull/681/files

**Comment by cndoit18** [comment]
Of course, we have to ensure that the upstream changes will not affect us after migrating to the go modules.

**Comment by shlomi-noach** [comment]
> We have successfully switched to go modules!

How did you deal with the changes in `raft` library?

> Next, we can add a cache. same like Dockerfile

Sorry, which cache is that? Do you mean a go mod proxy?

> And migrated to golang 1.16

Sorry again, I'm confused. How do you mean?

**Comment by cndoit18** [comment]
> > We have successfully switched to go modules!
> 
> How did you deal with the changes in `raft` library?
> 
> > Next, we can add a cache. same like Dockerfile
> 
> Sorry, which cache is that? Do you mean a go mod proxy?
> 
> > And migrated to golang 1.16
> 
> Sorry again, I'm confused. How do you mean?

Sorry, please forgive me for bad English, so that there is no expression clear

I use `https://github.com/openark/raft`, you already have
Docker uses layers when building, if you first use go mod download, the follow-up to build images can be reused.
You are still using golang1.14 image, which can be upgraded to golang1.16.

**Comment by cndoit18** [comment]
https://petomalina.medium.com/using-go-mod-download-to-speed-up-golang-docker-builds-707591336888
You can see this

**Comment by shlomi-noach** [comment]
> I use https://github.com/openark/raft, you already have

Can you believe that I completely forgot that I did?

> Docker uses layers when building, if you first use go mod download, the follow-up to build images can be reused.

I understand now. Shall we do it in a separate PR?

> You are still using golang1.14 image, which can be upgraded to golang1.16.

I understand. We can it now, right?

**Comment by cndoit18** [comment]
> > I use https://github.com/openark/raft, you already have
> 
> Can you believe that I completely forgot that I did?
> 
> > Docker uses layers when building, if you first use go mod download, the follow-up to build images can be reused.
> 
> I understand now. Shall we do it in a separate PR?
> 
> > You are still using golang1.14 image, which can be upgraded to golang1.16.
> 
> I understand. We can it now, right?

Yes, we do it in a separate PR

**Comment by cndoit18** [comment]
> > You are still using golang1.14 image, which can be upgraded to golang1.16.
> 
> I understand. We can it now, right?

Your code has used too many shell scripts. For me, it is very difficult

**Comment by shlomi-noach** [comment]
> Your code has used too many shell scripts. For me, it is very difficult

No problem. I can do this in a different PR. I am grateful to you for this work.

**Comment by cndoit18** [comment]
> > Your code has used too many shell scripts. For me, it is very difficult
> 
> No problem. I can do this in a different PR. I am grateful to you for this work.

Thank you

**Comment by shlomi-noach** [comment]
I pushed some final changes to the branch: I ran `go mod tidy && go mod vendor` and committed the changes.

**Comment by cndoit18** [comment]
> I pushed some final changes to the branch: I ran `go mod tidy && go mod vendor` and committed the changes.

cool

**Comment by cndoit18** [comment]
> I pushed some final changes to the branch: I ran `go mod tidy && go mod vendor` and committed the changes.

squash commits into one.

**Comment by shlomi-noach** [comment]
I'm gonna review this in a few more days and hopefully merge by end of week.

**Review by shlomi-noach — APPROVED** [review]

**Pull request merged**
