### PR TITLE
Add PowerAuthGroups: users in these unix groups get admin access

### PR DESCRIPTION
**Pull request by sjmudd**
This simplifies the configuration and avoiding the need to have to explicitly name all PowerAuthUsers. If the authenticated user is in the given list of groups then they will be given "admin" / write access.

So you can change what may be a large list of 
```
  "PowerAuthUsers": ["usera", "userb", "userc", "...", "userz", "api_user1", "api_user2" ],
```

with something like
```
  "PowerAuthGroups": [ "orchestrator_users_group", "orchestrator_api_users_group" ],
```

That is put the user in the right unix group and orchestrator will be happy.  Note: this does assume that you are using something like nginx to provide the authentication service etc.

- [x] contributed code is using same conventions as original code
- [x] code is formatted via `gofmt` (please avoid `goimports`)
- [x] code is built via `./build.sh`

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Thank you -- this looks real good. Would you mind moving this away from the `http` package and into the `os` package?

**Comment by sjmudd** [comment]
ok, will do.

**Review by shlomi-noach — APPROVED** [review]

**Comment by sjmudd** [comment]
So moved the files as requested to os, and fixed a small issue noted with go vet / golint.

**Comment by sjmudd** [comment]
Thanks for the fast response.

**Pull request merged**
