### PR TITLE
Add topology tags command

### PR DESCRIPTION
**Pull request by nickdelnano**
Related issue: https://github.com/github/orchestrator/issues/941

### Description

This PR adds a command "topology-tags" to the HTTP API and the CLI interface to act exactly like the "topology" command but also to print the tags for each instance on the same line as the instance itself.

A proposal for the text formatting is specified in #941, but copied here:

```
$ orchestrator -c topology -i testhost:22293
testhost:22293     [unknown,unchecked,5.6.28-log,rw,STATEMENT,>>,P-GTID]
- testhost:22294   [unknown,unchecked,5.6.28-log,rw,STATEMENT,>>,P-GTID]
  - testhost:22295 [unknown,unchecked,5.6.28-log,rw,STATEMENT,>>,P-GTID]
- testhost:22296   [unknown,unchecked,5.6.28,rw,nobinlog,P-GTID]
- testhost:22297   [unknown,unchecked,5.6.28-log,rw,STATEMENT,>>,P-GTID]

$ orchestrator -c tag -i testhost:22293 -t in_service
$ orchestrator -c tag -i testhost:22293 -t role=backup

$ orchestrator -c tag -i testhost:22294 -t role=delayed

$ orchestrator -c tag -i testhost:22295 -t in_service

# The command which I am proposing, here I call it "topology-tags"
$ orchestrator -c topology-tags -i testhost:22295
testhost:22293     [unknown,unchecked,5.6.28-log,rw,STATEMENT,>>,P-GTID] [in_service,role=backup]
- testhost:22294   [unknown,unchecked,5.6.28-log,rw,STATEMENT,>>,P-GTID] [role=delayed]
  - testhost:22295 [unknown,unchecked,5.6.28-log,rw,STATEMENT,>>,P-GTID] [in_service]
- testhost:22296   [unknown,unchecked,5.6.28,rw,nobinlog,P-GTID] []
- testhost:22297   [unknown,unchecked,5.6.28-log,rw,STATEMENT,>>,P-GTID] []
```

I chose to add a separate command for this functionality instead of modifying "topology" or "topology-tabulated" in order to not modify existing APIs.

There is no option for printing tags for a tabulated topology, though this could be added if desired.

### Testing
I added an integration test following the same pattern as the testing of the "topology" command, which invokes the orchestrator CLI to call the command which is added in this PR.

I did not see unit tests for the functions which I modified in `go/inst/instance_topology.go` so I did not add any. I also did not add any tests for the HTTP endpoint for the new command since I see only minimal testing in `go/http/api_test.go`, though I did run orchestrator in http mode and `curl`ed the new endpoint and invoked it with the modified `orchestrator-client` script from this PR.

> In case this PR introduced Go code changes:

- [x] contributed code is using same conventions as original code
- [x] code is formatted via `gofmt` (please avoid `goimports`)
- [x] code is built via `./build.sh`
- [x] code is tested via `go test ./go/...`

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Thank you and sorry for the slow response. Getting to this in a few days.

**Comment by nickdelnano** [comment]
Hi @shlomi-noach , can you let me know whether this is a PR you are interested in reviewing (and considering for submission) ?

**Comment by shlomi-noach** [comment]
Terribly sorry for the delay. Please understand my current workload demands my attention at other places, I can still be slow to look into this -- please bare with me.

**Comment by shlomi-noach** [comment]
Sorry about the delay; I expect to look into & merge a bunch of community PRs during the first two weeks of October.

**Review by shlomi-noach — APPROVED** [review]
Again, apologies for the delay.

Thank you for this PR, for keeping inline with the existing coding conventions, for adding tests. This looks good!

**Pull request merged**
