### PR TITLE
Support countLostReplicas in failover hooks

### PR DESCRIPTION
**Pull request by shlomi-noach**
`{countLostReplicas}` is now reported to `PostFailoverProcesses` and `PostUnsuccessfulFailoverProcesses`

### CODE REVIEW

**Comment by shlomi-noach** [comment]
works as expected

**Comment by IT-xiaoge** [comment]
Under what conditions will Lost replicas？Now I will also lose replicas when failing over.

**Comment by shlomi-noach** [comment]
> Under what conditions will Lost replicas？Now I will also lose replicas when failing over.


Explained in https://github.com/github/orchestrator/blob/master/docs/topology-recovery.md#discussion-recovering-a-dead-master

**Comment by pospelov-v** [comment]
Hi. Command line text replacement its it `countLostReplicas`. Which Environment variable? `ORC_COUNT_LOST_REPLICAS`?

**Pull request merged**
