### PR TITLE
make the configuration race detector safe.

### PR DESCRIPTION
**Pull request by sjmudd**
The go race detector notices that we may overwrite the configuration
while reading it as there are no locks to prevent this.  This is
most likely to happen when you send SIGHUP to the running process
as it is quite busy.

So replace config.Config with config.Config() and return a copy of
the pointer to the configuration.

Load() Reload() and ForceReload() have been adjusted to use locking
and to also create a new copy of the configuration rather than
modify the existing one. The new copy then replaces the original
configuration and this process is surrounded by locking.  Configuration
modifications by the application are now done via calls which also
lock.

- [x] contributed code is using same conventions as original code
- [x] code is formatted via `gofmt` (please avoid `goimports`)
- [x] code is built via `./build.sh`
- [x] code is tested via `go test ./go/...`

### CODE REVIEW

**Review by shlomi-noach — APPROVED** [review]
This looks good. Have you ran this in prod under `-race`?

**Comment by shlomi-noach** [comment]
You need to apply same changes in `*_test.go` files.

**Review by shlomi-noach — CHANGES_REQUESTED** [review]
apply same changes in `*_test.go` files

**Comment by sjmudd** [comment]
Please hold off on applying this. I want to test more first. It's probably ok but also with the other PRs you have pending (the use TLS if necessary and some missing patches of mine) it probably will need  to be adjusted.

**Comment by sjmudd** [comment]
Going to close this. I'll come back to it again later.

**Pull request closed without merging**
