### PR TITLE
Update support for go 1.12 (also triggers some file reformatting)

### PR DESCRIPTION
**Pull request by sjmudd**
Orchestrator build fails on go1.12 so adjust.

```
[user@host ~/src/orchestrator/src/github.com/github/orchestrator]$ go version
go version go1.12 darwin/amd64
[user@host ~/src/orchestrator/src/github.com/github/orchestrator]$ ./build.sh -b
Build only; no packaging
go version must be between 1.8 and 1.10
```

This also triggers some file reformatting (due to `go fmt` changes) which I've included.
There are no functional changes in the code.

- [x] contributed code is using same conventions as original code
- [x] code is formatted via `gofmt` (please avoid `goimports`)
- [x] code is built via `./build.sh`

### CODE REVIEW

**Comment by sjmudd** [comment]
Related: https://github.com/github/orchestrator/pull/857.

**Review by shlomi-noach — COMMENTED** [review]
@sjmudd thank you. Can you please also remove go1.8, and update the `.travis.yml` file?

**Comment by shlomi-noach** [comment]
Because `go1.12` has different formatting than previous versions, `go1.12` will be the _minimal_ supported version. I don't wish to support both `1.11` and `1.12` with differing formatting.

**Comment by shlomi-noach** [comment]
Added:

- using go1.12 on Travis
- using go1.12 in Docker
- Updated `script/ensure-go-installed`

**Pull request merged**
