### PR TITLE
implement to get the cluster_domain for {failureClusterDomain}

### PR DESCRIPTION
**Pull request by tom--bo**
## A Pull Request should be associated with an Issue.

> We wish to have discussions in Issues. A single issue may be targeted by multiple PRs.
> If you're offering a new feature or fixing anything, we'd like to know beforehand in Issues,
> and potentially we'll be able to point development in a particular direction.

Related issue: https://github.com/github/orchestrator/issues/969

> Thank you! We are open to PRs, but please understand if for technical reasons we are unable to accept each and any PR

### Description

- Add cluster_domain column at SELECT_LIST in GetReplicationAnalysis()'s query.
- Set it to ClusterDetails.ClusterDomain.

> In case this PR introduced Go code changes:

- [x] contributed code is using same conventions as original code
- [x] code is formatted via `gofmt` (please avoid `goimports`)
- [x] code is built via `./build.sh`
- [ ] code is tested via `go test ./go/...`

No test code for this, but I already deployed my company's test-environment and there is no problem.

### CODE REVIEW

**Review by shlomi-noach — APPROVED** [review]
Thank you, this PR looks good.

**Comment by mostafahussein** [comment]
@tom--bo is this issue that you are trying to solve is the reason behind a new cluster is created when a master is dead and a slave promoted to master ?

**Comment by shlomi-noach** [comment]
Sorry about the delay; I expect to look into & merge a bunch of community PRs during the first two weeks of October.

**Comment by tom--bo** [comment]
@mostafahussein Sorry about late reply.
> @tom--bo is this issue that you are trying to solve is the reason behind a new cluster is created when a master is dead and a slave promoted to master ?

This PR may not match your situation...
Please see the issue https://github.com/github/orchestrator/issues/969 which I want to solve by this PR

**Pull request merged**
