### PR TITLE
raft support for SetClusterAliasManualOverride

### PR DESCRIPTION
**Pull request by MOON-CLJ**
Related issue: https://github.com/github/orchestrator/issues/775

### Description

cluster_alias_override info need raft support。

cc @yangeagle

### CODE REVIEW

**Review by shlomi-noach — APPROVED** [review]
looks good, and `cluster_alias_override` already covered in `snapshot_data.go`

**Comment by MOON-CLJ** [comment]
force push just add a new line in end of go/logic/command_applier.go。

**Comment by shlomi-noach** [comment]
please avoid force-pushing, just add more commits, is the way I prefer PRs here.

**Comment by MOON-CLJ** [comment]
@shlomi-noach okay, got.

**Comment by MOON-CLJ** [comment]
@shlomi-noach need help to check the test failure，please。

**Comment by shlomi-noach** [comment]
Restarted the build. I think this is a Travis mistake.

**Pull request merged**
