### PR TITLE
 Candidate databse instance: database native time

### PR DESCRIPTION
**Pull request by shlomi-noach**
This PR resubmits https://github.com/github/orchestrator/pull/587 with only the actual code change. See discussion on #587 and #585 

cc @ndelnano

### CODE REVIEW

**Comment by nickdelnano** [comment]
thank you @shlomi-noach !

**Comment by nickdelnano** [comment]
Is a date for the next release planned? The dates of the last several releases does not look like there is a fixed schedule.

**Comment by shlomi-noach** [comment]
You are correct, there is no fixed schedule. But a kind reminder helps!

**Comment by shlomi-noach** [comment]
While this may work well for `sqlite`, this breaks `MySQL` for servers with non-UTC timezone. Looking into.

**Comment by shlomi-noach** [comment]
We need to juggle between three different scenarios:

- MySQL backend (has timezone notion)
- Sqlite (does not have timezone notion)
- `raft` messages (`register-candidate` can apply by reading historical `raft` event, the value of `now()` becomes meaningless)

**Comment by shlomi-noach** [comment]
@ndelnano I ended up solving the problem in a different way: reading the timestamp as a string from the database, then feeding it back.
Would you care to test this PR works for you? Works for me, on `sqlite` and `MySQL` on different timezone boxes.

**Comment by nickdelnano** [comment]
@shlomi-noach I have tested and it does indeed work for me. Thanks again!

**Comment by shlomi-noach** [comment]
OK good, this has been deployed to staging and in production for a while. I'll let our daily tests run and then merge.

**Pull request merged**
