### PR TITLE
Supporting graceful master takeover and master-take via GUI

### PR DESCRIPTION
**Pull request by shlomi-noach**
Work in progress to allow graceful master takeover via GUI.

I'm unsatisfied about the inconsistency of the GUI. See https://github.com/github/orchestrator/issues/322#issuecomment-339582772

### CODE REVIEW

**Comment by shlomi-noach** [comment]
I'm satisfied with current solution: depending on where in the target `div` one drops a server, the operation is interpreted as `relocate` or `take-master` or `graceful-master-takeover`.


screen shot 2017-10-27 at 18 55 48
screen shot 2017-10-27 at 18 55 39
screen shot 2017-10-27 at 18 55 03
screen shot 2017-10-27 at 18 54 58

**Comment by shlomi-noach** [comment]
@92161898515 I'd like to confirm you're not a bot. Can you comment on why you approve changes?

**Comment by shlomi-noach** [comment]
@92161898515 is blocked.

**Comment by shlomi-noach** [comment]
closes https://github.com/github/orchestrator/issues/322

**Comment by zmoazeni** [comment]
@shlomi-noach I know it's early and this is super experimental, but I just tried the latest master (https://github.com/github/orchestrator/commit/11ff2b07ebfff3aa43cb7c87b8f943bbb24c14c4) with this PR merged in and the instructions here doesn't seem to work for me: https://github.com/github/orchestrator/issues/322#issuecomment-340236706

screenshot from 2017-10-31 16-08-12

No matter where I grab on from `instance-b594`, trying to drop it onto `instance-f1ed` (no matter where) always results in a `relocate` action.

I'm off to take the kids trick-or-treating but I can get you more diagnostic info later, or perhaps debug the JS on my side to see what's preventing `instance-b594` from gracefully taking over for `instance-f1ed`.

For what it's worth `orchestrator -c graceful-master-takeover` works fine and takes over as expected.

I'm running Ubuntu 17.10 with Chrome 62.0.3202.75 and I don't see any javacript errors in the browser console.

**Comment by shlomi-noach** [comment]
My first guess would be: Force-refresh your browser to remove `orchestrator.js` and `cluster.js` from cache.

**Comment by shlomi-noach** [comment]
It is also my final guess, judging from your screenshot: the UI look a bit different today, and so it is obvious your browser is caching the scripts as well as CSS.

**Comment by zmoazeni** [comment]
Bah that was entirely my problem. Sorry for the noise! (I upgraded the `orchestrator` binary but just spaced out on also updating the assets)

**Pull request merged**
