### PR TITLE
Fix integration tests for MySQL 5.7

### PR DESCRIPTION
**Pull request by bbuchalter**
Closes https://github.com/github/orchestrator/issues/608.

To really prove this, we'd need to update Travis to run on MySQL 5.7,
but I'm not sure that's really in-scope right now.

### CODE REVIEW

**Review by shlomi-noach — APPROVED** [review]
Looking good, thank you!

Asking Travis to run `5.7` is a good idea and I'm all for it.

**Review by shlomi-noach — CHANGES_REQUESTED** [review]
Request to change `last_partial_success`

**Comment by shlomi-noach** [comment]
Hmmm my inline comment seems to have gone lost. `last_check_partial_success` is better set as `1`. Thus, `,0,'full',0,0,0,'OFF');` should change to `,1,'full',0,0,0,'OFF');` throughout the code.

**Comment by bbuchalter** [comment]
Feedback addressed and rebased on master.

**Review by shlomi-noach — APPROVED** [review]

**Comment by shlomi-noach** [comment]
My mistake, and `last_check_partial_success` should have been `0`. I pushed the necessary fix.

**Comment by shlomi-noach** [comment]
@bbuchalter  please do not `force push` in this repository, as some of our internal testing gets upset about that. Thanks!

**Comment by shlomi-noach** [comment]
resubmitted as https://github.com/github/orchestrator/pull/649

**Comment by shlomi-noach** [comment]
Closing: superseded by https://github.com/github/orchestrator/pull/649

**Pull request closed without merging**
