### PR TITLE
Instance tags

### PR DESCRIPTION
**Pull request by shlomi-noach**
Work in progress to add tagging capabilities. This has come up by several use cases.

The user will be able to tag any instance by multiple tags.
Tags will be of `tag_name=tag_value` nature.

It will be possible to get the list of tags for an instance, list all instance which have a specific `tag_name=tag_value` or just happen to have `tag_name` regardless of the value.

It will be possible to set a tag (adds or replaces) or delete a tag.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Documentation available: https://github.com/github/orchestrator/blob/0e43004ab41fcc45111a9151e5e0628b03176570/docs/tags.md

To be merged early 2019

**Comment by shlomi-noach** [comment]
Added `untag-all` docs: https://github.com/github/orchestrator/blob/e9a0078f138c0d9fdca0e90a6d250a54f82cb9f4/docs/tags.md

**Comment by nickdelnano** [comment]
hi @shlomi-noach , from my understanding of this PR and interacting with the "tags" CLI, it seems that this information is not integrated into the "orchestrator -c topology" command.

I am potentially interested in submitting a patch to add an option to the topology command in order to output the tags for all instances in the cluster for which the topology is requested.

For example,

```
orchestrator-client -c topology -alias main -tags
10-64-126-194-uswest1aprod:3306     [0s,ok,5.7.23-log,rw,ROW,>>,P-GTID] role=master, cluster=main
+ 10-64-70-25-uswest1aprod:3306     [0s,ok,5.7.23-log,ro,ROW,>>,P-GTID] role=replica, cluster=main
  + 10-64-101-83-uswest1aprod:3306  [0s,ok,5.7.23-log,ro,ROW,>>,P-GTID] role=replica, cluster=main
```

If I created this patch, could it be considered for merging into the project?

**Comment by shlomi-noach** [comment]
Hi @ndelnano,
This makes sense. Ideally it would look like this:
```
10-64-126-194-uswest1aprod:3306     [0s,ok,5.7.23-log,rw,ROW,>>,P-GTID,role=master,cluster=main]
+ 10-64-70-25-uswest1aprod:3306     [0s,ok,5.7.23-log,ro,ROW,>>,P-GTID,role=replica,cluster=main]
  + 10-64-101-83-uswest1aprod:3306  [0s,ok,5.7.23-log,ro,ROW,>>,P-GTID,role=replica,cluster=main]
```

We'd also want to make sure it's added to `-c topology-tabulated`. If you open a PR, I may experiment and modify the output formatting.

Two pro-tips:
- Use three backtics to format code (see how I formatted your previous comment)
- Open a new issue as opposed to commenting on a merged PR.

**Pull request merged**
