### PR TITLE
Handle basic_auth variable properly when ORCHESTRATOR_API has credentials

### PR DESCRIPTION
**Pull request by sjmudd**
## A Pull Request should be associated with an Issue.

Resolves some pending issues in https://github.com/github/orchestrator/pull/675.

See the other issue for details.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Please have a look at https://github.com/github/orchestrator/pull/681 by our mutual friend @cezmunsta , to make sure this isn't duplicate work

**Comment by sjmudd** [comment]
I think my option should be simpler. Not sure.

**Comment by sjmudd** [comment]
It will use credentials if they are in `ORCHESTRATOR_API`, it will use `basic _auth` if set and won't use anything if neither has any values.

**Comment by sjmudd** [comment]
Just to make this comment here: https://github.com/github/orchestrator/pull/681 also works for me, so I'm happy for you to take that PR as offered first.

**Comment by shlomi-noach** [comment]
superseded by https://github.com/github/orchestrator/pull/681. @sjmudd please confirm

**Pull request closed without merging**
