### PR TITLE
Updated github.com/go-sql-driver/mysql to the master HEAD.

### PR DESCRIPTION
**Pull request by maurosr**
Fixes bug https://github.com/go-sql-driver/mysql/issues/536 so now the same TLS config does not need to be registered for each host and with different name (I am working on the ability to have mixed TLS and non-TLS connections to different nodes of the topology).

Also, an interesting effect noticed: after the upgrade of the driver there was a 20% decrease of median poll time to orchestrator backend.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
> Also, an interesting effect noticed: after the upgrade of the driver there was a 20% decrease of median poll time to orchestrator backend.

very interesting indeed.

**Comment by shlomi-noach** [comment]
@maurosr can you kindly ping me after this had been deployed at your company for a few days in production? I like nothing better than knowing this runs successfully on X,000 servers.

**Comment by maurosr** [comment]
Will do (3 hours running in production by now and is looking good).

**Comment by maurosr** [comment]
@shlomi-noach everything looks fine in production with the driver upgrade.

**Comment by shlomi-noach** [comment]
Ok cool. I'll merge shortly

**Comment by maurosr** [comment]
Sorry, forgot to make a new branch for TLS. I'll revert and create another PR for that.

**Pull request merged**
