### PR TITLE
ChangeMasterCredentials: fixed when server is not a replica

### LINKED ISSUE #788: MakeCoMaster fails, when master does not have any replication settings
If master does not have replication settings, i.e. `slave slave status` is "Empty set", the attempt to make it as co-master with the slave fails with the error:

> ChangeMasterTo: Cannot change master on: master1:3306 because replication is running

As far as I understand it fails in `ChangeMasterCredentials` function, checking whether replication is stopped or not:
```
	if !instance.ReplicationThreadsStopped() {
		return instance, fmt.Errorf("ChangeMasterTo: Cannot change master on: %+v because replication is running", *instanceKey)
	}
```
But replication is neither stopped nor running. I suppose, it is "ReplicationThreadStateNoThread".
PS: this is latest version 3.0.14 issue.

### PR DESCRIPTION
**Pull request by shlomi-noach**
Fixes https://github.com/github/orchestrator/issues/788

This fixes the `ChangeMasterCredentials()` behavior on masters. Behavior was broken by https://github.com/github/orchestrator/pull/767

cc @pasha167

### CODE REVIEW

**Comment by ghost** [comment]
@shlomi-noach, thank you for quick response. 
I tested that and it did not solve the issue. Could you please double check?
Thanks.

**Comment by shlomi-noach** [comment]
whoops. committed an unrelated change.

**Comment by shlomi-noach** [comment]
@pasha167 please test again now

**Comment by ghost** [comment]
Yes, that works 👍. Thanks.

**Comment by shlomi-noach** [comment]
This PR also introduces a concurrency cap on the number of replicas operated on `relocate-replicas`. There will only be 5 replicas moved at a time.

**Pull request merged**
