### PR TITLE
Display region, data center, and environment in UI

### LINKED ISSUE #1094: [Feature] Display region, data center, and environment in UI
These three bits of metadata are extremely useful, but not displayed anywhere in the UI — unless I am just missing something. Also the outline coloring of DCs in the cluster screen is helpful to see which instances are co-located; however, there is no legend or key to show which DC corresponds to which color.

Incoming PR to address this.

### PR DESCRIPTION
**Pull request by jhriggs**
The region, data center, and physical environment bits of metadata are not currently displayed in the UI, though instances have a colored outline/border to distinguish DCs. This adds all 3 pieces of information to the instance modal window and also the title/tooltip for each instance in the cluster screen. (The latter has been tested on FF, Chrome, and Safari on OS X, but the embedded new lines may not work in all browsers.) This also adds a legend to the bottom of the cluster screen that shows the mapping of outline color to DC.

Fixes #1094.

### CODE REVIEW

**Comment by jhriggs** [comment]
This is what it looks like:

image (1)

image (3)

image (2)

**Comment by shlomi-noach** [comment]
Thank you for this pull request and sorry about the delays. This looks overall good and makes sense. I may tweak the UI a bit and circle back here.

**Comment by shlomi-noach** [comment]
I'm suggesting this visual change:

Screen Shot 2020-04-28 at 10 51 44 AM

In the above, the legend matches the cluster display format.

**Review by shlomi-noach — APPROVED** [review]
Thank you for this PR. I've made some visual changes, as well as took anonymization and dc-coloring into account when rendering the legend.

**Pull request merged**
