### PR TITLE
Small aesthetical reformat of /web/status

### PR DESCRIPTION
**Pull request by maurosr**
Separated running_since into its own column and added column names into /web/status.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Thank you! Since this is a visual change, can you attach a screenshot of the new look?

**Comment by maurosr** [comment]
status_page_reformat

**Comment by shlomi-noach** [comment]
Thanks. Seems to me like this may be a screenshot of the existing state? What's changed?

**Comment by shlomi-noach** [comment]
Sorry I see it now.

**Comment by maurosr** [comment]
Previously Running Since was in the same column as the hostname and also the columns didn't have names
screen shot 2017-06-23 at 20 38 53

**Review by shlomi-noach — APPROVED** [review]

**Pull request merged**
