### PR TITLE
Test for "Access denied for user" to trigger TLS

### LINKED ISSUE #541: Accounts requiring an encrypted connection fail to be discovered
When `MySQLTopologyUseMutualTLS` is `false`, accounts that require an encrypted connection fail during discovery.

```
$ orchestrator-client -c all-instances | wc -l
0

$ mysql -h 192.168.56.20 -Bse "select user, ssl_type from mysql.user where user = 'orchestrator'"
orchestrator    ANY

$ egrep MySQLTopologyUse\(Mutual\|Mixed\)TLS /etc/orchestrator.conf.json
  "MySQLTopologyUseMutualTLS": false,

$ orchestrator-client -c discover -i 192.168.56.20:3306
Error 1045: Access denied for user orchestrator@monitor (using password: YES)
```

Checking for `Access denied for user` in `requiresTLS` triggers the switch to TLS mode
and discovery is then possible.

### PR DESCRIPTION
**Pull request by cezmunsta**
To fix https://github.com/github/orchestrator/issues/541
```
$ ln -f /usr/local/orchestrator/orchestrator.requireTLSfix /usr/local/orchestrator/orchestrator; systemctl restart orchestrator.service

$ orchestrator-client -c discover -i 192.168.56.20:3306
192.168.56.20:3306

$ orchestrator-client -c all-instances | wc -l
1

$ orchestrator-client -c all-instances | wc -l
2

$ orchestrator-client -c topology -a db1
192.168.56.20:3306   [0s,ok,5.7.21-21-log,rw,ROW,>>]
+ 192.168.56.21:3306 [0s,ok,5.7.21-21-log,ro,ROW,>>]
```

### CODE REVIEW

**Review by shlomi-noach — APPROVED** [review]
Thank you!

**Review by shlomi-noach — COMMENTED** [review]
Question: does `Access denied for user` necessarily mean a TLS setup? Will the same message not fire for a "normal" problem with credentials?

**Comment by cezmunsta** [comment]
@shlomi-noach the "access denied for user" could indeed appear for normal failure of credentials. However, because `requiresTLS` is only called [if `MySQLTopologyUseMixedTLS` is enabled](https://github.com/github/orchestrator/blob/master/go/db/db.go#L91) this seemed to be an acceptable tradeoff as TLS is "expected". If you feel that there is a better way to resolve this issue then please apply that instead.

**Comment by shlomi-noach** [comment]
@cezmunsta thank you. This seems reasonable.

**Pull request merged**
