### PR TITLE
Proper indentation for pseudo-gtid sql and docs update

### PR DESCRIPTION
**Pull request by calind**
* proper indentation for `pseudo-gtid.sql`
* updated docs with the script from `resources/pseudo-gtid/pseudo-gtid.sql`

### CODE REVIEW

**Review by shlomi-noach — COMMENTED** [review]
can you please merge recent changes, namely your very own merged PR that checks for `read_only`?

**Comment by calind** [comment]
It is merged. The PR is based on current master (v2.0.2).

**Comment by shlomi-noach** [comment]
Ah, yes. I got confused because you added the `drop view` invocation under the `GET_LOCK` check.

**Review by shlomi-noach — APPROVED** [review]
thank you

**Pull request merged**
