### PR TITLE
Fix Orchestrator Favicon

### LINKED ISSUE #444: Favicon not loading
I see that a favicon is referenced in [layout.tmpl#L10](https://github.com/github/orchestrator/blob/4f68f5bf3e389e72a25fc7558823af25b219ca09/resources/templates/layout.tmpl#L10) but that file doesn't exist.

### PR DESCRIPTION
**Pull request by ushuz**
I added a color-inverted orchestrator logo as favicon, as the original light grey one doesn't look good as a favicon.

image

Close #444

### CODE REVIEW

**Comment by yakirgb** [comment]
Nice

**Review by shlomi-noach — APPROVED** [review]
Belated thank you!

**Comment by ushuz** [comment]
@shlomi-noach Hi, it seems that this PR is not properly merged. Instead, the master branch was merged into this PR.

**Comment by shlomi-noach** [comment]
Right. I merged master into this branch to get it up to date, but never merged back. Meeting now. Thanks again

**Pull request merged**
