### PR TITLE
WIP: orchestrator/kubernetes

### PR DESCRIPTION
**Pull request by shlomi-noach**
All things `kubernetes`. Or at least all public things.

### CODE REVIEW

**Comment by derekperkins** [comment]
Has any progress been made on this?

**Comment by shlomi-noach** [comment]
Some, internal, and not the the point where I'm satisfied to publish...

**Comment by hmilkovi** [comment]
Any news?

**Comment by shlomi-noach** [comment]
Heh, great resurrection of an old issue. No, sorry. There was no progress made and I don't expect to be working on this.

**Pull request closed without merging**
