### PR TITLE
Bump Go versions and use '.x' to always get latest patch versions

### PR DESCRIPTION
**Pull request by HaraldNordgren**

### CODE REVIEW

**Review by shlomi-noach — CHANGES_REQUESTED** [review]
I'm not yet prepared to use `1.11`. Please see https://github.com/github/orchestrator/pull/639

**Comment by shlomi-noach** [comment]
Still happy for `1.10` though

**Comment by HaraldNordgren** [comment]
@shlomi-noach Fair enough. Removed 1.11.

**Review by shlomi-noach — APPROVED** [review]

**Review by AlekSi — APPROVED** [review]
:shipit:

**Comment by HaraldNordgren** [comment]
@shlomi-noach @AlekSi Rebased on master :)

**Comment by shlomi-noach** [comment]
oh, sorry for dropping this.

**Pull request closed without merging**
