### PR TITLE
Add discovery queue timing metrics and make available via http api calls

### PR DESCRIPTION
**Pull request by sjmudd**
Add the following api calls which provide raw and aggregated discovery
queue metrics:

* /api/discovery-queue-metrics-raw/:seconds
* /api/discovery-queue-metrics-aggregated/:seconds

- [x] contributed code is using same conventions as original code
- [x] code is formatted via `gofmt` (please avoid `goimports`)
- [x] code is built via `./build.sh`
- [x] code is tested via `go test ./go/...`

### CODE REVIEW

**Review by shlomi-noach — APPROVED** [review]
Can you please add comment with example of output?

**Comment by sjmudd** [comment]
ok, I've added a couple of example outputs to give you an idea of what can be collected. Hopefully this is ok now.

**Comment by shlomi-noach** [comment]
@sjmudd sorry I meant as comment to this PR, rather than `txt` file in `src/go`

**Review by shlomi-noach — CHANGES_REQUESTED** [review]
Sorry I meant if you can add examples as comment into the PR. If you can please take this file out of the source  tree (just delete it?)

**Comment by sjmudd** [comment]
Example outputs

Below are some sample outputs from the discovery queue api:

(1) `https://orchestrator.mycompany.com/api/discovery-queue-metrics-raw/60` returns
`[{"Active":4,"Queued":0},{"Active":37,"Queued":0},{"Active":5,"Queued":0},{"Active":4,"Queued":0},{"Active":4,"Queued":0},{"Active":4,"Queued":0},{"Active":4,"Queued":0},{"Active":4,"Queued":0},{"Active":29,"Queued":0},{"Active":4,"Queued":0},{"Active":5,"Queued":0},{"Active":3,"Queued":0},{"Active":4,"Queued":0},{"Active":138,"Queued":0},{"Active":23,"Queued":0},{"Active":3,"Queued":0},{"Active":4,"Queued":0},{"Active":5,"Queued":0},{"Active":4,"Queued":0},{"Active":6,"Queued":0},{"Active":4,"Queued":0},{"Active":4,"Queued":0},{"Active":4,"Queued":0},{"Active":18,"Queued":0},{"Active":4,"Queued":0},{"Active":4,"Queued":0},{"Active":4,"Queued":0},{"Active":5,"Queued":0},{"Active":94,"Queued":0},{"Active":5,"Queued":0},{"Active":6,"Queued":0},{"Active":4,"Queued":0},{"Active":4,"Queued":0},{"Active":5,"Queued":0},{"Active":13,"Queued":0},{"Active":4,"Queued":0},{"Active":5,"Queued":0},{"Active":4,"Queued":0},{"Active":4,"Queued":0},{"Active":4,"Queued":0},{"Active":22,"Queued":0},{"Active":41,"Queued":0},{"Active":4,"Queued":0},{"Active":170,"Queued":0},{"Active":52,"Queued":0},{"Active":23,"Queued":0},{"Active":5,"Queued":0},{"Active":6,"Queued":0},{"Active":5,"Queued":0},{"Active":6,"Queued":0},{"Active":11,"Queued":0},{"Active":5,"Queued":0},{"Active":5,"Queued":0},{"Active":7,"Queued":0},{"Active":6,"Queued":0},{"Active":6,"Queued":0},{"Active":6,"Queued":0},{"Active":5,"Queued":0},{"Active":153,"Queued":0},{"Active":11,"Queued":0}]`

(2) `https://orchestrator.mycompany.com/api/discovery-queue-metrics-aggregated/60` returns
`{"ActiveMinEntries":2,"ActiveMeanEntries":13.5,"ActiveMedianEntries":5,"ActiveP95Entries":66,"ActiveMaxEntries":167,"QueuedMinEntries":0,"QueuedMeanEntries":0,"QueuedMedianEntries":0,"QueuedP95Entries":0,"QueuedMaxEntries":0}`

**Comment by sjmudd** [comment]
I've fixed some conflicts and merged in again. Hopefully this is good. If not I can do this again more cleanly.

**Review by shlomi-noach — APPROVED** [review]
Thank you

**Pull request merged**
